<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageId>Snitch.Core</PackageId>
        <Authors>dotfelix</Authors>
        <RepositoryUrl>https://github.com/dotfelix/Snitch</RepositoryUrl>
        <PackageProjectUrl>https://github.com/dotfelix/Snitch</PackageProjectUrl>
        <Description>Real-time exception alerting for .NET Core apps</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>Exception, Alerting, Slack</PackageTags>
        <Version>1.0.4</Version> 
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ISnitch.fs" />
        <Compile Include="Slack.fs" />
        <Compile Include="ServiceLocator.fs" />
        <Compile Include="SnitchExtension.fs" />
        <Compile Include="SnitchMiddleware.fs" />
        <Compile Include="SnitchService.fs" />
        <Compile Include="ServiceCollectionExtension.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup> 

</Project>
